name: traking_screen
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  device_info_plus: ^3.2.2
  double_back_to_close: ^2.0.0
  easy_debounce: ^2.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_vector_icons: ^1.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  http: ^0.13.4
  shamsi_date: ^1.0.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  flutter_test:
    sdk: flutter
    dev_dependencies: null
flutter_native_splash:

  
  color: "#42a5f5"
  
  image: assets/images/icon.png

 
  branding_mode: bottom
  
flutter:

  
  uses-material-design: true

  assets:
    - .env
    - assets/images/icon.png

 
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/Sans.ttf
    
